### ISSUE TITLE
ER_CONN_REFUSED when the  bus.Connect() is executed

### ISSUE THREAD

**Issue by RichardNieuwland** [dotMorten/AllJoynDotNet#1]
I tried both the test-method and the TestApp.NET45
any clue ?
The TestApp UWP is working fine, but i'm really looking for a .NET solution ..

**Comment by dotMorten** [comment]
@RichardNieuwland I've seen this a couple of times too, but haven't investigated in detail. From what I think is happening is you're either not connected to a network, or the network is set to "public" and not "private". Switching that made the error go away for me.

Note: I always see this issue on Android. No idea why there yet.

Thank you for trying this out btw. It's very much a work in progress, but at least a few bits are starting to work, but still lots to wrap, and p/invoke calls to fix.

**Comment by RichardNieuwland** [comment]
Tnx for the quick reply. Sometimes it helps trying it multiple times. :) . It can start the bus-connection now, still looking for the place to start an alljoyn producer. but i keep on searching.  tnx.
Am i wrong to think that the interface should be visible for the Alljoyn Explorer in win10 also ?

**Comment by dotMorten** [comment]
@RichardNieuwland There aren't any "Producers". That's an UWP Code generator concept built on top of the lower level AllJoyn API ;-)

The project is far from complete enough to actually build a device with this. Currently focused on trying to get the samples from the AllJoyn repos working. Getting close to complete the AllJoyn About Client: https://github.com/allseenalliance/core-alljoyn/blob/master/alljoyn_c/samples/about/about_client.cc

The "producer" would be the equivalent `about_service.cc` sample in the same samples folder.

And yes the AllJoyn Explorer will work with this once complete.
