### ISSUE TITLE
Using the generated code for Xamarin.iOS

### ISSUE THREAD

**Issue by abdelkader27** [dotMorten/AllJoynDotNet#3]
Hi,

Thank you for this work. I want to know if it's possible to use the generated interop code for Xamarin.iOS with the builded Library .a?

**Comment by dotMorten** [comment]
@abdelkader27 I have not done the work for iOS at this point, but I don't see why this wouldn't work there as well. I do take contributions ;-)

**Comment by dotMorten** [comment]
See issue: https://github.com/dotMorten/AllJoynDotNet/issues/4

**Comment by abdelkader27** [comment]
I'm trying to compile the source code for Xamarin.Android but there's some errors:
- QStatus is not found
- some casting errors like comparaison of int and intptr

Is there something to do with that?

thanks.
