### ISSUE TITLE
Compilation error for Android

### ISSUE THREAD

**Issue by abdelkader27** [dotMorten/AllJoynDotNet#6]
I'm trying to compile the source code for Xamarin.Android but there's some errors:

```
 •QStatus is not found

 •some casting errors like comparaison of int and intptr
```

Is there something to do with that?

thanks.

**Comment by dotMorten** [comment]
@abdelkader27 The first issue should be fixed. Let me know if you're still seeing this. I'm not clear on the second issue. I would need a few more details, but please try again. Lots have changed.

**Comment by abdelkader27** [comment]
Hi, thank you it's compiling fine now.
